const i18Obj = {
  en: {
    contacts: 'Contacts',
    about: 'About me',
    skills: 'Skills',
    code: 'Code',
    codeExample: 'Code example',
    education: 'Education',
    projects: 'Projects',
    languages: 'Languages',
    name: 'Olga Andrievich',
    aboutDescription: `For me, programming is about finding new ways to solve problems,
    developing better creativity, reasoning and critical thinking.
    Besides I really like the visual effect of the executable code. So
    my goal is to become a skilled front-end developer and implement
    cool web resources.`,
    residence: 'Russian Federation, Moscow',
    university_1: 'Irkutsk State Linguistic University',
    speciality_1: 'Speciality: Theoretical and Applied Linguistics',
    university_2:
      'Siberian State University of Telecommunications and Informatics',
    speciality_2: 'Speciality: Information Science and Engineering',
    coursesTechJS: 'Course: JavaScript/Front-end (RS School)',
    coursesTechReact: 'Course: React (RS School)',
    сode: 'Code Example',
    english: 'English (fluent)',
    russian: 'Russian (native)',
    german: 'German (advanced threshold)',
    portfolio: `Photographer's Portfolio`,
    birds: 'Birds Songs',
    quotes: 'Random Quotes',
    memory: 'Memory Game',
    rsLang: 'RS Lang (language learning app)',
    rickAndMorty: 'Rick and Morty',
    projectManagementApp: 'Project Management App',
  },
  ru: {
    contacts: 'Контакты',
    about: 'Обо мне',
    skills: 'Навыки',
    code: 'Код',
    codeExample: 'Пример кода',
    education: 'Образование',
    projects: 'Проекты',
    languages: 'Языки',
    name: 'Ольга Андриевич',
    aboutDescription: `Для меня программирование — это поиск новых способов решения задач, развитие творческих способностей, логического и критического мышления. Кроме того, мне очень нравится визуальный эффект исполняемого кода. Моя цель — стать квалифицированным фронтенд-разработчиком и реализовывать качественные веб-приложения.`,
    residence: 'Россия, Москва',
    university_1: 'Иркутский Государственный Лингвистический Университет',
    speciality_1: 'Специальность: Теоретическая и прикладная лингвистика',
    university_2:
      'Сибирский государственный университет телекоммуникаций и информатики',
    speciality_2: 'Специальность: Информатика и вычислительная техника',
    coursesTechJS: 'Курс JavaScript/Front-end (RS School)',
    coursesTechReact: 'Курс по React (RS School)',
    russian: 'Русский (родной)',
    english: 'Английский (продвинутый)',
    german: 'Немецкий (пороговый продвинутый уровень)',
    portfolio: 'Портфолио фотографа',
    birds: 'Пение птиц',
    quotes: 'Случайные цитаты',
    memory: 'Игра на запоминание',
    rsLang: 'RS Lang (приложение для изучения языка)',
    rickAndMorty: 'Рик и Морти',
    projectManagementApp: 'Система управления проектами',
  },
};
export default i18Obj;
